- skyfield/tests/test_timelib.py
- skyfield/timelib.py
- new error message for when a tuple is accidentally passed into a function wrapped with takes_julian_date decorator
- adds test to ensure that this new tuple error message is the exception raised
- more documentation to JulianDate to link the time scale abbreviations to full names, as well as mentioning that the float is a Julian day representation.
- removed references to ut1 / the fifth time scale (ut1 was removed long ago, but the docstring still referenced it)
> Adds error message for accidental tuple and expands JulianDate's docstring

- README.rst
The link for Skyfield package on PyPI is duplicated.
> Remove duplicated line on the Readme

- skyfield/tests/test_timelib.py
- skyfield/timelib.py
This pull request contains a few short tests that cover the issues I've been finding with Time (#98 and #99).
It also contains fixes for them:
- For #98 I've added a branch that deals with filling in missing values of delta_t correctly for scalar inputs.
- For #99 I've added a branch to `__repr__` that produces output for the array valued case. It takes it cues from how `skyfield.units.Angle` outputs, giving the number of values and the range.
Hope it's of some use!
> Tests and fixes for issues in Time (delta_t and __repr__)

- skyfield/tests/test_timelib.py
- skyfield/timelib.py
This pull request is a fix for #102.
I've also added some unit tests to check the conversion of calendar_tuple/julian_date, and wrapped the input of calendar_tuple in a `_to_array` call to stop it failing if called with a Python scalar argument.
> Fix for calendar_tuple

- skyfield/sgp4lib.py
`EarthSatellite.__init__()` now caches the timescale as a class variable Instead of loading it each time.
This increases the speed of the initialization by ~100x (from ~20 ms to ~0.23 ms), which is relevant when loading complete satellite catalogs (3 minutes to 2 seconds).
This is 20x slower than pyephem, but fast enough that the speed difference is usually not relevant.
This is the fix to issue #116 .  If the same code is in the stand-alone sgp4 library it should be propagated there as well.
> Issue #116: EarthSatellite now caches the timescale 

- skyfield/iokit.py
`os.path.remove(path)` is throwing an error.
Should be `os.remove(path)`.
> Fix bug in `Loader.open` method

- skyfield/elementslib.py
- skyfield/tests/test_elementslib.py
Fixes the reference_frame keyword of `osculating_elements_of`, which currently isn't working. This also makes the rest of the tests (currently marked broken) pass.
> Fix reference_frames keyword in elementslib

- skyfield/documentation/elements.rst
I changed the attributes to regular text instead of inline code so the arrows would line up. I also made the lines continuous between categories of elements so the table would be more similar to the table in ``positions.rst``.
> Make OsculatingElements attribute table look better

- skyfield/elementslib.py
- skyfield/tests/test_elementslib.py
The repr still used OsculatingElements.size which was removed, this PR fixes that, and adds a test to make sure the repr is working as expected.
> Fix osculating elements repr

- skyfield/elementslib.py
Raises a ValueError instead of having a mysterious numpy divide by zero warning later on
> Check if mu is zero in OsculatingElements.__init__()

- skyfield/sgp4lib.py
- skyfield/tests/test_earth_satellites.py
According to the [SPICE toolkit documentation](https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/FORTRAN/req/naif_ids.html#Earth%20Orbiting%20Spacecraft.):
>If an Earth orbiting spacecraft lacks a DSN identification code, the NAIF ID is derived from the tracking ID assigned to it by NORAD via:
>
>      NAIF ID = -100000 - NORAD ID code
>
>For example, NORAD assigned the code 15427 to the NOAA 9 spacecraft. This code corresponds to the NAIF ID -115427.
I confirmed that the satellite numbers in TLEs are the NORAD ID code by checking in [this file from celestrak](https://celestrak.com/NORAD/elements/noaa.txt) that the satellite number for NOAA 9 is in fact 15427.
I wasn't sure if you would want a test or not, so I included one just in case.
> Make EarthSatellite target attribute the NAIF id

- .travis.yml
- requirements.txt
- setup.py
- skyfield/almanac.py
- skyfield/documentation/almanac.rst
- skyfield/tests/test_satellite_almanac.py
Draft pull request for Issue #115 .
Documentation and tests included.
(Tests cause a deprecation warning: np.float64->int .  How do I breakpoint to find where that happens?)
Usage:
```
t, y = almanac.find_satellite_events(t0, t1,
satellite=satellite, topos=bluffton, horizon=10)
altitude, azimuth, distance = almanac.satellite_altitude(
satellite=satellite, topos=bluffton, time=t, and_azdist=True)
```
Only covers rise/culminate/set.
Solar illumination may be added in a later issue.
> Satellite events almanac functions.

- skyfield/iokit.py
Skyfield's `iokit.py` is currently using the `cafile` keyword in `urlopen`, which is deprecated from Python 3.6 on (see the deprecation note at the very end of the `urlopen` section here: https://docs.python.org/3/library/urllib.request.html#urllib.request.urlopen). This PR updates the call to `urlopen` to use what I think to be the intended replacement.
While in principle a minor issue, it turns out to lead very indirectly to some failing tests downstream - see astropy/astropy#10200 for more detail on what lead me down this path... But regardless of the downstream effect, this would seem to be more what the current python standard library intends!
> Update urlopen call to not use deprecated cafile keyword

- skyfield/errors.py
- skyfield/jpllib.py
Add support for the `OutOfRangeError` exception thrown by JplEphem in brandon-rhodes/python-jplephem#36.
Basically, we catch the raised exception on JplEphem's side and re-throw a Skyfield-specific one with the times converted in `Time` objects.
Fix #319
> Throw exception if calculation time is out of range

- skyfield/errors.py
- skyfield/tests/test_api.py
Fixing a small mistake introduced in commit c2181134d70a2a8ba104ba0db5b39b6cb633263a, in the constructor of the new `EphemerisRangeError`.
> Fix typo in the EphemerisRangeError constructor

- skyfield/iokit.py
Currently the `EarthSatellite` class is instantiated with a `ts` `kwarg`, but if you instantiate via the `Loader.parse_tle_file()` method, `ts` specification is lost. I added a simple pass through in the form of a `ts` `kwarg` for `Loader.tle_file()` and `Loader.parse_tle_file()` so that the `EarthSatellite` instances created by the `parse_tle_file()` generator can have specific timescales.
> Added timescale passthrough for EarthSatellite instantiation via Loader.tle_file()

- skyfield/documentation/earth-satellites.rst
- skyfield/sgp4lib.py
This is a first pass. I tried to match as much as possible, but I'd be happy to restructure/reconfigure if you'd like. This is to add the feature I requested in https://github.com/skyfielders/python-skyfield/issues/362
I obviously pulled heavily from https://space.stackexchange.com/questions/37713/how-can-i-calculate-if-a-satellite-is-currently-in-sunlight-or-eclipse-using-pye/40217#40217 (as in copied and cleaned it up). 
I added documentation for usage, let me know if there is anything else I should add beyond that. (Wasn't sure about testing, since it's really just geometry and vector math)
> Added is_sunlit method and docs for usage - Issue #362

- skyfield/keplerlib.py
- skyfield/tests/test_keplerlib.py
This fixes #432 by removing checks that were to strict in the function `keplerlib.ele_to_vec`. They were too strict because they disallowed any orbit whose elements couldn't be exactly reversed by the OsculatingElements object even if they were valid, i.e. element sets that have a non-zero value for an indeterminate element. I added tests to make sure no errors occur in these cases.
I also found that the check for inclinations was too strict and disallowed inclinations of exactly pi (retrograde equatorial orbits). I added tests for different types of retrograde equatorial orbits.
> Remove checks that are too strict in ele_to_vec

- skyfield/keplerlib.py
- skyfield/tests/test_keplerlib.py
The `elements_at_epoch` attribute of the `_KeplerOrbit` object is referring to a nonexistent attribute of the `_KeplerOrbit` class, this PR fixes it.
> Fix nonexistent attribute in `_KeplerOrbit` object

- skyfield/searchlib.py
Pass `epsilon`and `num` parameters from `find_minima` to `find_maxima`.
I'd like to take advantage of this PR to add documentation about these parameters and the `rough_period` attribute set to the function, since they seem very important in the calculation. Personally, I've always failed to really understand what their purpose is. Can you explain these, so I can update the docs?
> Fix find_maxima call in find_minima function

- skyfield/keplerlib.py
I was a little disappointed that this refactoring gave me a pretty much negligible speed increase.
But it's clearly a win in readability and ease of further vectorization, so I shouldn't complain too much 😀.
Also I learned a new code smell: lots of uses of `np.tile` and `np.repeat` means I'm probably broadcasting by hand instead of letting Numpy do its job.
> Refactor `keplerlib.stumpff`

- skyfield/data/mpc.py
- skyfield/functions.py
- skyfield/keplerlib.py
I have successfully vectorized `keplerlib.propagate`! All of it's arguments can now be arrays. Just for testing purposes I added a function to `data/mpc.py` that can take a comets dataframe and convert it into a `_KeplerOrbit` object that represents multiple comets.
At the moment `_KeplerOrbit` objects that represent multiple orbits don't play well with other `VectorFunction` objects; I'm not sure what needs to change to fix that.
I haven't added any tests yet since none of the official functions in `data/mpc.py` can handle multiple orbits at a time yet.
Here's an example script:
```
from skyfield.api import Loader
from skyfield.data import mpc
from skyfield.constants import GM_SUN_Pitjeva_2005_km3_s2 as GM_SUN
from numpy import arange, linspace, rollaxis
import matplotlib.pyplot as plt …
```
> Vectorized `keplerlib.propagate`

- skyfield/documentation/examples.rst
I found this bug when looking into discussion #597.
The example script [here](https://rhodesmill.org/skyfield/examples.html#when-will-it-get-dark-tonight) defines `previous_e` as an `ndarray` of size 1. This isn't a problem as long as the first branch of the if statement is used, but the second branch uses `previous_e` as a key to the `almanac.TWILIGHTS` dictionary which expects an integer, thus causing the error.
I was originally going to suggest using `np.isscalar` to convert the `ndarray` to an integer, but the [documentation](https://numpy.org/doc/stable/reference/generated/numpy.asscalar.html) says that function is deprecated and recommends the `item()` method instead.
> Fix bug in twilight calculation example script

- .gitignore
- design/sgp4_parallel.py
This is an updated prototype to test package the parallel SGP4 capability for computing "n satellites x m times" into one routine in Skyfield.
The new function `positions_for(satellites, earthLocation, times)` takes an array of EarthSatellite objects, a `Topos` earth location and an array of `Time` and yields a position for each satellite provided. Some basic tests verify that the positions are `np.isclose()` to calculating positions one satellite at a time.
> Updated: Prototype support for parallel SGP4 across multiple satellites

- skyfield/tests/test_elementslib.py
- skyfield/tests/test_planetarylib.py
- skyfield/tests/test_positions.py
Tested on Ubuntu 22.10 x86_64
Python 3.11.2
nunpy 1.23.5 and 1.24.2
Closes #822
> Fix compatibility with numpy >= 1.23.5

- skyfield/documentation/earth-satellites.rst
Updated the documentation with correct units for ndot and nddot.
Related: https://github.com/brandon-rhodes/python-sgp4/pull/115
From the other PR for reference:
In the project documentation, ndot is specified as units "revs/day" and nddot is "revs/day^3", however the actual implemented units are radians/minute^2 and radians/minute^3. This PR just brings the documentation in line with the code.
See following examples:
```python
>>> from sgp4.api import Satrec
>>> from astropy.units import Quantity
>>> # Parse a TLE with:
>>> #   ndot = .00000205 revs/day^2
>>> #   nddot = 0.2125e-5 revs/day^3
>>> #                                          ndot       nddot
>>> line1 = "1 00005U 58002B   23070.26627551  .00000205  21250-5  25732-3 6  9996"
>>> line2 = "2 00005  34.2487  37.1068 1845867 …
```
> Fixed units of ndot and nddot in earth-satellites.rst.

- skyfield/functions.py
This pull request avoids using the _AVOID_DIVIDE_BY_ZERO term in two cases.
> Use arctan2 instead of arcsin when converting to spherical coordinates
